### ISSUE TITLE
Net Label Connection

### ISSUE THREAD

**Issue by innovation-plantation** [innovation-plantation/jsimugate#7]
Create a symbol (such as a diamond) with a mandatory alphanumeric identifier name 
as a text label (first character must be a letter) as a "part" with a single connection. 
Anything connected to another net label connection with the same identifier name
will be treated as  connected together when analyzing the circuit.

**Comment by appender** [comment]
Dr. Ted,

I assume that you solved this issue with the Reference part?  That was a pretty ingenious solution, and I would not have been able to come up with that.  I'll continue to check your issues tab, and look forward to finding something that I can help with.  

Thanks,

-Alex Pendergrast
CS 266

**Comment by innovation-plantation** [comment]
Added
