### ISSUE TITLE
Out of date documentation

### ISSUE THREAD

**Issue by jwheeler31** [innovation-plantation/jsimugate#9]
I attempted to recreate one of the examples found here https://github.com/innovation-plantation/jsimugate/wiki/processor, specifically the data bus-program counter-address bus, but could not for the life of me find the component labeled "EN". This looks like an interesting project.

**Comment by innovation-plantation** [comment]
Start with a 3-state gate and expand it to have more pins

**Comment by innovation-plantation** [comment]
Documentation clarified
